/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.app

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testApp() {
        assert(true)
    }
}
